# Generated by Django 5.0.14 on 2026-08-18 17:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_workerprofile_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
