# Generated by Django 5.0.14 on 2026-08-23 17:50

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_last_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='document',
            field=models.FileField(upload_to=config.storage_backends.unique_upload_path('certifications')),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('user_photos')),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('id_documents')),
        ),
    ]
