# Generated by Django 5.0.14 on 2026-08-26 16:45

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('id_documents')),
        ),
    ]
