# Generated by Django 5.0.14 on 2026-08-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workerprofile_id_document_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biometric_enabled',
        ),
    ]
