# Generated by Django 5.0.14 on 2026-08-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_biometric_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='code',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='code_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
