# Generated by Django 5.0.14 on 2026-08-28 06:14

import config.storage_backends
import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_phoneotp_code_phoneotp_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='document',
            field=models.FileField(upload_to=config.storage_backends.unique_upload_path('certifications'), validators=[config.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('user_photos'), validators=[config.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('id_documents'), validators=[config.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='id_document_back',
            field=models.FileField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('id_documents'), validators=[config.validators.validate_file_size]),
        ),
    ]
