from django.urls import path

from .views import (
    AcceptOfferView,
    ArrivedView,
    BlockCounterpartView,
    CompleteJobView,
    ConfirmQuoteView,
    DeclineJobView,
    DeclineOfferView,
    DisputePriceView,
    JobCancelView,
    JobRequestDetailView,
    JobRequestListCreateView,
    MessageListCreateView,
    NearbyJobsView,
    QuoteView,
    RateJobView,
    RejectQuoteView,
    ReportJobView,
    StartJobView,
    WorkerIncomingOfferView,
    WorkerStatusView,
)

urlpatterns = [
    path("", JobRequestListCreateView.as_view(), name="job-list-create"),
    path("nearby/", NearbyJobsView.as_view(), name="jobs-nearby"),
    path("worker/status/", WorkerStatusView.as_view(), name="worker-status"),
    path("worker/incoming/", WorkerIncomingOfferView.as_view(), name="worker-incoming"),
    path("offers/<int:pk>/accept/", AcceptOfferView.as_view(), name="offer-accept"),
    path("offers/<int:pk>/decline/", DeclineOfferView.as_view(), name="offer-decline"),
    path("<int:pk>/", JobRequestDetailView.as_view(), name="job-detail"),
    path("<int:pk>/cancel/", JobCancelView.as_view(), name="job-cancel"),
    path("<int:pk>/arrived/", ArrivedView.as_view(), name="job-arrived"),
    path("<int:pk>/quote/", QuoteView.as_view(), name="job-quote"),
    path("<int:pk>/decline/", DeclineJobView.as_view(), name="job-decline"),
    path("<int:pk>/confirm-quote/", ConfirmQuoteView.as_view(), name="job-confirm-quote"),
    path("<int:pk>/reject-quote/", RejectQuoteView.as_view(), name="job-reject-quote"),
    path("<int:pk>/start/", StartJobView.as_view(), name="job-start"),
    path("<int:pk>/complete/", CompleteJobView.as_view(), name="job-complete"),
    path("<int:pk>/dispute-price/", DisputePriceView.as_view(), name="job-dispute-price"),
    path("<int:pk>/rate/", RateJobView.as_view(), name="job-rate"),
    path("<int:pk>/report/", ReportJobView.as_view(), name="job-report"),
    path("<int:pk>/block/", BlockCounterpartView.as_view(), name="job-block"),
    path("<int:pk>/messages/", MessageListCreateView.as_view(), name="job-messages"),
]
