# Generated by Django 5.0.14 on 2026-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobrequest_accepted_at_jobrequest_worker_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
