# Generated by Django 5.0.14 on 2026-08-23 17:50

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_cancellationlog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('job_photos')),
        ),
    ]
