# Generated by Django 5.0.14 on 2026-08-28 06:14

import config.storage_backends
import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobrequest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.unique_upload_path('job_photos'), validators=[config.validators.validate_file_size]),
        ),
    ]
