# Generated by Django 5.0.14 on 2026-08-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobrequest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.message'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('no_show', 'No-show'), ('safety_concern', 'Safety concern'), ('quality_of_work', 'Quality of work'), ('pricing_disagreement', 'Pricing disagreement'), ('harassment', 'Harassment or abusive language'), ('inappropriate_content', 'Inappropriate content'), ('spam', 'Spam or scam'), ('other', 'Other')], max_length=30),
        ),
    ]
