# Generated by Django 5.0.14 on 2026-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_report_message_alter_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='on_my_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
