# Generated by Django 5.0.14 on 2026-09-08 19:59
# Active-job & pricing flow v2 (docs/prds/active-job-flow-v2.md):
#  - status enum: drop on_my_way + awaiting_price_confirmation, add
#    quote_pending / quote_accepted / declined
#  - drop on_my_way_at, add quoted_at / quote_accepted_at
#  - CancellationLog.kind (cancellation | on_site_decline)
# Prod had no real job data at write time; the data migration below only
# matters for the shared local/dev database.

from django.db import migrations, models


def remap_removed_statuses(apps, schema_editor):
    JobRequest = apps.get_model("jobs", "JobRequest")
    JobRequest.objects.filter(status="on_my_way").update(status="accepted")
    JobRequest.objects.filter(status="awaiting_price_confirmation").update(
        status="quote_pending"
    )


def noop_reverse(apps, schema_editor):
    # Not reversible — the old on_my_way / awaiting_price_confirmation
    # distinction and on_my_way_at timestamps are gone. Left as a no-op so
    # `migrate jobs 0007` doesn't hard-fail.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobrequest_arrived_at_jobrequest_on_my_way_at_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_removed_statuses, noop_reverse),
        migrations.RemoveField(
            model_name='jobrequest',
            name='on_my_way_at',
        ),
        migrations.AddField(
            model_name='cancellationlog',
            name='kind',
            field=models.CharField(choices=[('cancellation', 'Cancellation'), ('on_site_decline', 'On-site decline')], default='cancellation', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='quote_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('quote_pending', 'Quote pending'), ('quote_accepted', 'Quote accepted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('disputed', 'Disputed')], default='requested', max_length=30),
        ),
    ]
